name: monad
description:
  practical monad implementation in dart-language.
version:
  0.5.5

repository:
  https://github.com/LouiS0616/DartyMonad

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety.12